package:
  name: ucc
  version: "0.1.0"

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - automake
    - libtool
    - make

  host:
    - ucx
    - cuda-toolkit
  run:
    - ucx
    - cuda-toolkit

# test:
#   commands:
#     - test -f $PREFIX/lib/ucc
