{% set cuda_version="12" %}

package:
  name: ucc
  version: v1.3.0.rc1

source:
  url: https://github.com/openucx/ucc/archive/refs/tags/v.1.3.0-rc1.tar.gz
  sha256: b553a5f12848586a6195a59e5938cd4f9d84c61159393e061a2b33c44616972e

build:
  skip: True  # [not linux]
  number: 0
  missing_dso_whitelist:
    - '*libcuda.so*'
  ignore_run_exports_from:
    - cuda-nvcc

requirements:
  build:
    - {{ compiler('cxx') }}
    - cuda-nvcc >={{ cuda_version }}
    - automake
    - libtool
    - make

  host:
    - ucx
    - cuda-cudart-dev

  run:
    - ucx
    - cuda-version >={{ cuda_version }}

test:
  commands:
    - test -f $PREFIX/lib/libucc$SHLIB_EXT

about:
  home: https://github.com/openucx/ucc
  summary: 'UCC is a collective communication operations API and library.'
  description: |
    UCC is a collective communication operations API and library that is flexible, complete, and feature-rich for current and emerging programming models and runtimes.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sandeepd-nv
